version: 1
jobs:
  build:
    docker:
      - image: circleci/node:11.6
    working_directory: ~/root

    steps:
      - checkout:
          path: ~/root
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: npm install
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: Run Test and Coverage
          command: |
            ./cc-test-reporter before-build
            npm test -- --coverage
            ./cc-test-reporter after-build --exit-code $?
  deploy:
    docker:
      - image: circleci/node:11.6
    working_directory: ~/root
    steps:
      - checkout:
          path: ~/root
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: create build
          command: CI=false npm run build
      - run:
          name: Install awscli
          command: sudo apt-get install awscli
      - run:
          name: Deploy to S3
          command: aws s3 sync build/ s3://travel-n-move-react-staging
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: development
